// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MixArchive.Data;

#nullable disable

namespace MixArchive.Data.Migrations
{
    [DbContext(typeof(MixArchiveDbContext))]
    [Migration("20261007164547_AddTags")]
    partial class AddTags
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("MixArchive.Models.Mix", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Mixes");
                });

            modelBuilder.Entity("MixArchive.Models.MixFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastScanned")
                        .HasColumnType("TEXT");

                    b.Property<int>("MixId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FileHash");

                    b.HasIndex("FileName")
                        .IsUnique();

                    b.HasIndex("MixId")
                        .IsUnique();

                    b.ToTable("MixFiles");
                });

            modelBuilder.Entity("MixArchive.Models.MixTag", b =>
                {
                    b.Property<int>("MixId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MixId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("MixTags");
                });

            modelBuilder.Entity("MixArchive.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("MixArchive.Models.MixFile", b =>
                {
                    b.HasOne("MixArchive.Models.Mix", "Mix")
                        .WithOne("File")
                        .HasForeignKey("MixArchive.Models.MixFile", "MixId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mix");
                });

            modelBuilder.Entity("MixArchive.Models.MixTag", b =>
                {
                    b.HasOne("MixArchive.Models.Mix", "Mix")
                        .WithMany("MixTags")
                        .HasForeignKey("MixId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MixArchive.Models.Tag", "Tag")
                        .WithMany("MixTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mix");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("MixArchive.Models.Mix", b =>
                {
                    b.Navigation("File");

                    b.Navigation("MixTags");
                });

            modelBuilder.Entity("MixArchive.Models.Tag", b =>
                {
                    b.Navigation("MixTags");
                });
#pragma warning restore 612, 618
        }
    }
}
